version: '3'
services:

  nginx2:
    image: nginx:latest
    container_name: 'nginx2'
    volumes:
      - ./html:/usr/share/nginx/html
      - ./etc/nginx/conf.d/:/etc/nginx/conf.d
    environment:
      VIRTUAL_HOST: 'blog2.nginx.com'
      LETSENCRYPT_HOST: 'blog2.nginx.com'
      LETSENCRYPT_EMAIL: 'example@blog2.nginx.com'


networks:
  default:
    external:
      name: shared